---
title: "Final Exam Winter 2021"
author: "Data Science for Managers"
date: "Code Interpretation"
output:
  html_document:
    code_folding: show
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
library(tidyverse)
library(nycflights13)
library(viridis)
library(sf)
library(maps)
```

### Read in the workspace

```{r companies data, echo = FALSE}
load(url("http://govfinance.byu.edu/govfinance/classes/dataScience/lectures/scripts/Final Exam Review/final review workspace.RData"))
```

### Code Chunk 1: Two different Pareto Charts

```{r code 1}
mpg %>% 
  count(class, sort = TRUE) %>% 
  ggplot(aes(x = class %>% fct_reorder(n) %>% fct_rev(), y = n)) +
  geom_col()

mpg %>% 
  ggplot(aes(x = class %>% fct_infreq())) +
    geom_bar()
```

### Code Chunk 2: Get county outlines and add population

```{r code chunk 2}
(
  counties <-
    maps::map("county", "utah", plot = FALSE, fill = TRUE) %>%
    sf::st_as_sf() %>%
    separate(
      col = ID,
      into = c("state", "county"),
      sep = ","
    ) %>%
    select(-state) %>%
    left_join(county_population) %>%
    mutate(population = population / 1000)
)
```

### Code Chunk 3: Draw a map with shading by county population

```{r code chunk 3}
counties %>%
  ggplot(aes(fill = population), color = gray(0.5)) +
  geom_sf() +
  scale_fill_viridis_c(trans = "log10", alpha = 0.5) +
  coord_sf(
    xlim = c(-115, -108),
    ylim = c(36.5, 42.5),
    expand = FALSE
  ) +
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()
  ) +
  labs(title = "The counties along the Wasatch front are most populous.",
       fill = "Thousands of People")
```

### Code Chunk 4: Location and scale of departure delays from JFK and LaGuardia

```{r code chunk 4}
flights %>%
  filter(origin != "EWR") %>%
  filter(dep_delay > 0) %>%
  group_by(origin) %>%
  summarise(
    median_delay = median(dep_delay, na.rm = TRUE),
    IQR_delay = IQR(dep_delay, na.rm = TRUE)
  ) %>%
  left_join(airports, c("origin" = "faa")) %>%
  select(name, median_delay, IQR_delay) %>%
  arrange(median_delay)
```

### Code Chunk 5: Presidential term graph

```{r code chunk 5}
presidential %>%
  mutate(id = 33 + row_number()) %>%
  ggplot(aes(start, id, color = party)) +
  geom_point(size = 4) +
  geom_segment(aes(xend = end, yend = id), size = 3) +
  scale_x_date(breaks = presidential$start, date_labels = "'%y") +
  scale_y_continuous(breaks = seq(34, 44, 1), labels = presidential$name) +
  scale_colour_manual(values = c("Republican" = "red", "Democratic" = "blue")) +
  theme(
    panel.grid.minor.x = element_blank(),
    panel.grid.minor.y = element_blank(),
    legend.position = "bottom"
  )
```
