---
title: "Homework #18"
author: "Iteration"
date: "25 March 2020"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
library(tidyverse)
library(nycflights13)
```

## Concepts  

1.  Explain the basic parts of a for loop. 

2.  Explain how loops are different from functions.
    
## Interpretation of code  

Code Chunk #1 (Section 21.2.1 Exercises Problem 1.3)

```{r number of unique values in the iris data frame}
unique_values <- vector("integer", length(iris))
for (i in seq_along(iris)) {
  unique_values[[i]] <- iris[[i]] %>% 
    unique() %>% 
    length()
}
unique_values
```

Code Chunk #2 (Section 21.3.4)

```{r while loop}
# flip a coin function
flip <- function() sample(c("T", "H"), 1)
# initialize variables
flips <- 0
nheads <- 0
# while loop
while (nheads < 3) {
  if (flip() == "H") {
    nheads <- nheads + 1
  } else {
    nheads <- 0
  }
  flips <- flips + 1
}
flips
```  

## Write Code

Compute the type for each column in the nycflights13::flights tibble. (The second part of the first problem from Exercises 21.2.1)

```{r type of variables in flights}

```

