---
title: "Homework #20"
author: "Shiny I"
date: "Due: 6 April 2020"
output:
  html_document:
    code_folding: "hide"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)
library(tidyverse)
```

## Concepts  

Explain the function and interaction of the ui and server parts of a shiny app.  

The section ui handles the interface between the user and R. This is where the user and interact by specifying input values. It is also where the calculations completed by R are reported and depicted.  

The section severs is the part of the shiny app that does the work and calculations. This is where statistical routines are run, plots are created, and tables assembled.  
    
## Interpretation of code  

### Interpret the following R code chunks: 

### Code Chunk #1 UI part of a shiny app

> ui <- fluidPage(

> titlePanel("Old Faithful Geyser Data"),

> sidebarLayout(

>  sidebarPanel(

> sliderInput("bins",
                       "Number of bins:",
                       min = 1,
                       max = 50,
                       value = 30)
                ),

>  mainPanel(

>  plotOutput("distPlot")
       )
   ) )

Line 1: Designates the code section as the ui or user interface and declares that the app should use fluidpage. This allows the Shiny app to adapt to the size of the screen of the device used to view the app.  

Line 2: Gives the title "Old Faithful Geyser Data" to the app.

Line 3: Provides the structure for the sidebar panel which is where the input will occur in this app.

Lines 4 - 9:  Creates a slider which creates a variable called bins. The title seen by the user is "Number of bins:". The slider has a minimum value of 1 and a maximum value of 50. The initial value of the slider is set to 30.

Line 10: Creates the section for the output that comes from the server.

Lne 11:  Plots the output distPlot. This plot was created in the server part of the app.

### Code Chunk #2 Server Part of a Shiny app

> server <- function(input, output) {

> output$distPlot <- renderPlot({

>  x <- faithful[, 2]

>  bins <- seq(min(x), max(x), length.out = input$bins + 1)

>  hist(x, breaks = bins, col = 'darkgray', border = 'white')})}

Line 1:  Declares a server function that has input and output as arguments  

Line 2:  Creates an object in the output list called distPlot which is the result of R code that creates a graph.  

Line 3:  Assigns the variable x to the second column in the faithful tibble.  

Line 4:  Creates a new variable called bins which is a sequence that starts at the minimum value of x and ends at the maximum value of x. The length of the sequence is the number of bins inputed from the slider in the ui plus 1.  

Line 5:  Creates a histogram of x (the second column in faithful) with breaks that come from the sequence specified in line 4: the color of the histogram is "darkgray" and the border of the bars is "white".  

## Write Code

Alter the basic shiny app so that it draws a histogram with number of bins that are determined by the user for the hwy variable in the mpg tibble. Attach your R script file to your homework.

For the code, see the associated R script file.
