---
title: "Midterm 1 Fall 2019"
author: "Alex Dunlap"
date: "10/13/2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
flights <- nycflights13::flights
```

## Problem 1


```{r Problem 1}
flights %>%
  filter(dest =="ATL" | dest == "BOS", arr_delay >= -30 & arr_delay <= 30) %>%
  ggplot(aes(x = origin, y = arr_delay, fill = origin)) +
    geom_violin(show.legend = FALSE) +
    geom_boxplot(width = 0.2, outlier.size = 0.5, fill = "gray", show.legend = FALSE) +
    coord_flip() +
    facet_grid(rows = vars(dest)) +
    labs(x = "Origin", y = "Arrival Delay", title = "NYC 2013 Flights Within 30 Minutes of Scheduled Arrival")
```

## Problem 2


```{r Problem 2}
flights %>%
  filter(!is.na(dep_delay), !is.na(arr_delay), dep_delay < 0) %>%
  group_by(origin) %>%
  summarize(proportion = mean(arr_delay <= 0) * 100) %>%
  ggplot(aes(x = reorder(origin, desc(proportion)), y = proportion, fill = origin)) +
    geom_bar(stat = "identity", show.legend = FALSE) +
    labs(x = "", y = "Percentage", title = "Bar Chart (Pareto) of Percentage On Time")
```


