---
title: "HW16"
author: "Ray Nelson"
date: "11/16/2018"
output:
  html_document:
    code_folding: "hide"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(nycflights13)
```

#### 1. Compute the mean of every column in mtcars.

First we check to see the number and type of columns in mtcars.

```{r mtcars columns}
mtcars %>% glimpse()
```  

Now we write a for loop that computes the means for each of the  

```{r column means}
output <- vector("double", ncol(mtcars))
for (i in seq_along(mtcars)) {
  output[[i]] <- mtcars[[i]] %>% mean()
}
output
```  

#### 2. Determine the type of each column in nycflights13::flights  

```{r types of columns in flights}
types_of_columns <- vector("character", ncol(flights))
for (i in seq_along(flights)) {
  types_of_columns[[i]] <- flights[[i]] %>% typeof()
}
types_of_columns
```  

#### 3. Compute the number of unique values in each column of iris

```{r unique values}
number_unique <- vector("integer", ncol(iris))
for (i in seq_along(iris)) {
  number_unique[[i]] <- iris[[i]] %>% unique() %>% length()
}
number_unique
```  

#### 4. Generate 10 random normals with means of -10, 0, 10, and 100

```{r random normals}
means <- c(-10, 0, 10, 100)
output <- list("double", 4)
for (i in 1:4) {
  output[[i]] <- rnorm(10, means[i])
}
output
```  

