---
title: "R4DS Chapter 14: Strings"
author: "Ray Nelson"
date: "10/4/2021"
output:
  html_document:
    code_folding: "show"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

### 14.2 String basics

Basic creation of strings

```{r basics}
(string1 <- "This is a string")
(string2 <- 'If I want to include a "quote" inside a string, I use single quotes.')
writeLines(string2)
```

Using \\ to create strings from codes and use writeLines

```{r quote marks}
(double_quote <- "\"")
(single_quote <- "\'")
writeLines(double_quote)
writeLines(single_quote)
x <- c("\"", "\\")
writeLines(x)
```

Special characters

```{r code for mu}
(x <- "\u00b5")
```

Multiple strings in a character vector

```{r multiple strings}
c("one", "two", "three", "four")
```

#### 4.2.1 String Length

```{r string length}
str_length(c("a", "R for data science", NA))
```

#### 4.2.2 Combining strings

```{r combining strings}
str_c("x", "y")
str_c("x", "y", "z")
str_c("x", "y", sep = ", ")
```

What to do when you have an NA

```{r NAs }
x <- c("abc", NA)
str_c("|-", x, "-|")
str_c("|-", str_replace_na(x), "-|")
```

Strings are vectorized

```{r vectorized strings}
str_c("prefix-", c("a", "b", "c"), "-suffix")
```

Objects of zero length are silently dropped

```{r drop zero length}
name <- "Hadley"
time_of_day <- "morning"
birthday <- FALSE

str_c(
  "Good ", time_of_day, " ", name,
  if(birthday) " and HAPPY BIRTHDAY",
  "."
)
```

Collapse a vector of strings into a single string

```{r collapse a string vector}
str_c(c("x", "y", "z"), collapse = ", ")
```

14.2.3 Subsetting strings
